apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lighty-clustering-chart.fullname" . }}
  labels:
    {{- include "lighty-clustering-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lighty-clustering-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lighty-clustering-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # When
            # akka.management.cluster.bootstrap.contact-point-discovery.port-name
            # is defined, it must correspond to this name:
            - name: management
              containerPort: 8558
              protocol: TCP
            # restconf port
            - name: restconf
              containerPort: 8888
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
