apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighty-clustering-chart.fullname" . }}
spec:
  ports:
    - protocol: TCP
      port: 8558
      name: http-akka
    - protocol: TCP
      port: 8888
      name: http-restconf
  selector:
    {{- include "lighty-clustering-chart.selectorLabels" . | nindent 4 }}
